Repository Estsoft-Udon/ClassicJeans, pull requests merged in 2024-11, with the labels that each got.

#4 docs: 풀리 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs, Fix

#7 chore: add CODEOWNERS file
  .github/CODEOWNERS
Labels: Setting

#10 feat: 초기 프로젝트 세팅
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Setting

#9 ci: main 브랜치로의 PR을 release 브랜치에서만 허용
  .github/workflows/validate-pr-to-main.yml
Labels: Setting

#18 style: package 구조 설정
  src/main/java/com/example/classicjeans/controller/UsersController.java
  src/main/java/com/example/classicjeans/dto/request/UsersRequest.java
  src/main/java/com/example/classicjeans/dto/response/UsersResponse.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/img/chungbazi.png
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: Design

#24 setting : RDS 연결, 임시 데이터베이스 : test
  src/main/resources/application.properties
Labels: Setting

#25 Feature: create entites / enums
  src/main/java/com/example/classicjeans/entity/Bazi.java
  src/main/java/com/example/classicjeans/entity/HealthData.java
  src/main/java/com/example/classicjeans/entity/HospitalData.java
  src/main/java/com/example/classicjeans/entity/NursingHomeData.java
  src/main/java/com/example/classicjeans/entity/ParentsInfo.java
  src/main/java/com/example/classicjeans/entity/SubsidyData.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/enums/Gender.java
  src/main/java/com/example/classicjeans/enums/Grade.java
Labels: Feature

#22 docs: 시퀀스 다이어그램 추가
  docs/diagrams/analytics/analysis.md
  docs/diagrams/chat/chat_function.md
  docs/diagrams/information/hospital.md
  docs/diagrams/information/nursing_home.md
  docs/diagrams/information/support_fund.md
  docs/diagrams/main/main_function.md
  docs/diagrams/user/account_management.md
  docs/diagrams/user/account_recovery.md
  docs/diagrams/user/authentication.md
  docs/diagrams/user/profile.md
Labels: Docs

#40 Release/v0.0.1
  docs/diagrams/analytics/analysis.md
  docs/diagrams/chat/chat_function.md
  docs/diagrams/information/hospital.md
  docs/diagrams/information/nursing_home.md
  docs/diagrams/information/support_fund.md
  docs/diagrams/main/main_function.md
  docs/diagrams/user/account_management.md
  docs/diagrams/user/account_recovery.md
  docs/diagrams/user/authentication.md
  docs/diagrams/user/profile.md
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/controller/UsersController.java
  src/main/java/com/example/classicjeans/dto/request/AlanHealthRequest.java
  src/main/java/com/example/classicjeans/dto/request/UsersRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanBasicResponse.java
  src/main/java/com/example/classicjeans/dto/response/UsersResponse.java
  src/main/java/com/example/classicjeans/entity/Bazi.java
  src/main/java/com/example/classicjeans/entity/HealthData.java
  src/main/java/com/example/classicjeans/entity/HospitalData.java
  src/main/java/com/example/classicjeans/entity/NursingHomeData.java
  src/main/java/com/example/classicjeans/entity/ParentsInfo.java
  src/main/java/com/example/classicjeans/entity/SubsidyData.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/enums/Gender.java
  src/main/java/com/example/classicjeans/enums/Grade.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/resources/application.properties
  src/main/resources/static/css/index.css
  src/main/resources/static/img/chungbazi.png
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: Deploy, Setting

#36 Feature/치매문진표 ai검사
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanDementiaResponse.java
  src/main/java/com/example/classicjeans/service/AlanService.java
Labels: Feature, Refactor

#39 feat: HealthData에 검진 타입 추가
  src/main/java/com/example/classicjeans/entity/HealthData.java
  src/main/java/com/example/classicjeans/enums/Analysis.java
Labels: Feature

#34 Feature/create users crud
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/UsersController.java
  src/main/java/com/example/classicjeans/dto/request/UsersRequest.java
  src/main/java/com/example/classicjeans/dto/response/UsersResponse.java
  src/main/java/com/example/classicjeans/entity/FamilyInfo.java
  src/main/java/com/example/classicjeans/entity/HealthData.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/java/com/example/classicjeans/util/DateFormatUtil.java
Labels: Feature

#52 Feature/프론트 페이지 작업
  build.gradle
  src/main/java/com/example/classicjeans/controller/MainController.java
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/layout.html
Labels: Feature

#50 Feature/기본문진표 ai 검사 기능
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanDementiaResponse.java
  src/main/java/com/example/classicjeans/dto/response/AlanQuestionnaireResponse.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/util/RegexPatterns.java
Labels: Feature, Refactor

#54 refactor: AlanService 코드 리팩토링
  src/main/java/com/example/classicjeans/service/AlanService.java
Labels: Refactor

#55 Release/v0.0.2
  build.gradle
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/admin/service/AdminService.java
  src/main/java/com/example/classicjeans/config/AppConfig.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/controller/MainController.java
  src/main/java/com/example/classicjeans/controller/NursingHomeController.java
  src/main/java/com/example/classicjeans/controller/UsersController.java
  src/main/java/com/example/classicjeans/dto/request/AlanBaziRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/dto/request/NursingHomeRequest.java
  src/main/java/com/example/classicjeans/dto/request/UsersRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanBaziResponse.java
  src/main/java/com/example/classicjeans/dto/response/AlanDementiaResponse.java
  src/main/java/com/example/classicjeans/dto/response/AlanQuestionnaireResponse.java
  src/main/java/com/example/classicjeans/dto/response/NursingHomeResponse.java
  src/main/java/com/example/classicjeans/dto/response/UsersResponse.java
  src/main/java/com/example/classicjeans/email/AuthCodeGenerator.java
  src/main/java/com/example/classicjeans/email/config/RedisConfig.java
  src/main/java/com/example/classicjeans/email/controller/AuthController.java
  src/main/java/com/example/classicjeans/email/controller/EmailController.java
  src/main/java/com/example/classicjeans/email/service/AuthService.java
  src/main/java/com/example/classicjeans/email/service/EmailService.java
  src/main/java/com/example/classicjeans/entity/FamilyInfo.java
  src/main/java/com/example/classicjeans/entity/HealthData.java
  src/main/java/com/example/classicjeans/entity/NursingHomeData.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/enums/Analysis.java
  src/main/java/com/example/classicjeans/repository/NursingHomeDataRepository.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/NursingHomeService.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/java/com/example/classicjeans/util/DateFormatUtil.java
  src/main/java/com/example/classicjeans/util/RegexPatterns.java
  src/main/resources/Chungbaji.md
  src/main/resources/application.properties
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/kakaomap.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/layout.html
Labels: Deploy, Docs

#56 Feature/hospital list
  src/main/java/com/example/classicjeans/config/HospitalConfig.java
  src/main/java/com/example/classicjeans/controller/HospitalController.java
  src/main/java/com/example/classicjeans/controller/HospitalViewController.java
  src/main/java/com/example/classicjeans/dto/request/HospitalRequest.java
  src/main/java/com/example/classicjeans/dto/response/HospitalResponse.java
  src/main/java/com/example/classicjeans/entity/Hospital.java
  src/main/java/com/example/classicjeans/repository/HospitalRepository.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/resources/static/js/hospital.js
  src/main/resources/templates/hospital.html
Labels: Feature

#63 Feature/front list
  src/main/java/com/example/classicjeans/config/HospitalConfig.java
  src/main/java/com/example/classicjeans/controller/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/SanatoriumViewController.java
  src/main/resources/static/css/header.css
  src/main/resources/static/css/info/list.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/img/logo.png
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/kakaomap.js
  src/main/resources/templates/hospital.html
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
Labels: Feature
