Repository Estsoft-Udon/ClassicJeans, pull requests merged in 2024-12, with the labels that each got.

#67 Feature/검사 결과 저장하는 기능
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanQuestionnaireResponse.java
  src/main/java/com/example/classicjeans/entity/DementiaData.java
  src/main/java/com/example/classicjeans/entity/HealthData.java
  src/main/java/com/example/classicjeans/entity/QuestionnaireData.java
  src/main/java/com/example/classicjeans/enums/Analysis.java
  src/main/java/com/example/classicjeans/enums/questionnaire/AlcoholConsumption.java
  src/main/java/com/example/classicjeans/enums/questionnaire/ChronicDisease.java
  src/main/java/com/example/classicjeans/enums/questionnaire/CommonFrequency.java
  src/main/java/com/example/classicjeans/enums/questionnaire/DietPattern.java
  src/main/java/com/example/classicjeans/enums/questionnaire/ExerciseFrequency.java
  src/main/java/com/example/classicjeans/enums/questionnaire/HospitalVisit.java
  src/main/java/com/example/classicjeans/enums/questionnaire/IndependenceLevel.java
  src/main/java/com/example/classicjeans/enums/questionnaire/Medication.java
  src/main/java/com/example/classicjeans/enums/questionnaire/MemoryChange.java
  src/main/java/com/example/classicjeans/enums/questionnaire/MoodStatus.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SleepPattern.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SmokingStatus.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SocialParticipation.java
  src/main/java/com/example/classicjeans/enums/questionnaire/WeightChange.java
  src/main/java/com/example/classicjeans/repository/DementiaDataRepository.java
  src/main/java/com/example/classicjeans/repository/QuestionnaireDataRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/util/RegexPatterns.java
  src/main/resources/Chungbaji.md
Labels: Feature, Refactor, Remove

#69 Feature/nursinghome sanatorium view
  src/main/java/com/example/classicjeans/controller/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/repository/NursingHomeDataRepository.java
  src/main/java/com/example/classicjeans/repository/SanatoriumDataRepository.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/java/com/example/classicjeans/service/NursingHomeService.java
  src/main/java/com/example/classicjeans/service/SanatoriumService.java
  src/main/resources/application.properties
  src/main/resources/static/js/kakaomap.js
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
Labels: Feature

#70 Feature/hospital
  src/main/java/com/example/classicjeans/controller/HospitalController.java
  src/main/java/com/example/classicjeans/controller/HospitalViewController.java
  src/main/java/com/example/classicjeans/dto/response/HospitalResponse.java
  src/main/java/com/example/classicjeans/entity/Hospital.java
  src/main/java/com/example/classicjeans/repository/HospitalRepository.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/resources/static/css/info/list.css
  src/main/resources/static/js/hospital.js
  src/main/resources/templates/info/hospital_list.html
Labels: Feature

#73 Feature/h list
  src/main/java/com/example/classicjeans/controller/HospitalController.java
  src/main/java/com/example/classicjeans/controller/HospitalViewController.java
  src/main/java/com/example/classicjeans/repository/HospitalRepository.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/resources/static/css/info/list.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/list.js
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
Labels: Design, Feature, Fix

#75 Feature/프론트 운세 임의의 데이터 노출
  src/main/java/com/example/classicjeans/controller/AlanBaziController.java
  src/main/java/com/example/classicjeans/controller/MainController.java
  src/main/java/com/example/classicjeans/dto/request/AlanBaziRequest.java
  src/main/java/com/example/classicjeans/entity/Bazi.java
  src/main/java/com/example/classicjeans/repository/AlanBaziRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: Feature

#79 Feature/front mypage
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/resources/static/css/member/member.css
  src/main/resources/static/css/reset.css
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/mypage.html
Labels: Feature

#81 Feature/create viewcontroller
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/controller/UsersController.java
  src/main/java/com/example/classicjeans/controller/ViewController.java
  src/main/java/com/example/classicjeans/dto/request/UsersRequest.java
  src/main/java/com/example/classicjeans/email/controller/EmailController.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/resources/static/css/member.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/js/find_pw.js
  src/main/resources/static/js/password_change.js
  src/main/resources/static/js/password_change_after_find.js
  src/main/resources/static/js/password_check.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/find_pw.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/signup.html
  src/main/resources/templates/member/success.html
  src/main/resources/templates/member/withdrawal.html
Labels: Feature, Refactor

#83 feature: security 세팅
  src/main/java/com/example/classicjeans/security/CustomAuthFailureHandler.java
  src/main/java/com/example/classicjeans/security/CustomUserDetails.java
  src/main/java/com/example/classicjeans/security/UsersDetailService.java
Labels: Feature

#85 Feature/front mypage
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/resources/static/css/member/member.css
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/withdrawal.js
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/edit_family.html
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/withdrawal.html
Labels: Feature

#87 Feature/user mypage
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/resources/static/js/nickname_check.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/signup.html
Labels: Feature

#89 Feature/create viewcontroller
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/java/com/example/classicjeans/controller/UsersController.java
  src/main/java/com/example/classicjeans/controller/ViewController.java
  src/main/java/com/example/classicjeans/email/controller/AuthController.java
  src/main/java/com/example/classicjeans/util/SecurityUtil.java
  src/main/resources/static/css/reset.css
  src/main/resources/static/img/google.png
  src/main/resources/static/img/kakao.png
  src/main/resources/static/img/naver.png
  src/main/resources/static/js/find_pw.js
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/login.html
Labels: Refactor

#91 Feature/create viewcontroller
  src/main/resources/static/js/signup.js
  src/main/resources/templates/layout/header.html
Labels: Fix

#93 Test/alan controller
  src/main/java/com/example/classicjeans/dto/response/AlanBaziResponse.java
  src/test/java/com/example/classicjeans/controller/AlanControllerTest.java
Labels: Test

#99 Feature/edit user information
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/resources/static/js/nickname_check.js
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/mypage.html
Labels: Design, Feature

#101 Feature/front member
  src/main/resources/static/css/chat.css
  src/main/resources/static/css/info/list.css
  src/main/resources/static/css/member/member.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/img/google2.png
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/find_pw.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/signup.html
Labels: Design, Feature, Fix

#107 Feature/oauth2
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/java/com/example/classicjeans/controller/ViewController.java
  src/main/java/com/example/classicjeans/dto/request/UsersRequest.java
  src/main/java/com/example/classicjeans/entity/Users.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/classicjeans/oauth/OAuthAttributes.java
  src/main/java/com/example/classicjeans/oauth/SessionUser.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/security/CustomUserDetails.java
  src/main/java/com/example/classicjeans/security/UsersDetailService.java
  src/main/resources/Chungbaji.md
  src/main/resources/application.properties
  src/main/resources/static/css/member.css
  src/main/resources/static/css/member/member.css
  src/main/resources/static/img/google.png
  src/main/resources/static/img/google2.png
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
  src/main/resources/templates/member/login.html
Labels: Feature, Fix, Refactor

#111 Feature/add family information
  src/main/java/com/example/classicjeans/controller/FamilyInfoController.java
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/java/com/example/classicjeans/dto/request/FamilyInfoRequest.java
  src/main/java/com/example/classicjeans/dto/response/FamilyInfoResponse.java
  src/main/java/com/example/classicjeans/entity/FamilyInfo.java
  src/main/java/com/example/classicjeans/repository/FamilyInfoRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/FamilyInfoService.java
  src/main/resources/static/js/edit_family.js
  src/main/resources/templates/member/edit_family.html
  src/main/resources/templates/member/mypage.html
Labels: Docs, Feature

#115 Feature/alen sse api
  build.gradle
  src/main/java/com/example/classicjeans/controller/ChatController.java
  src/main/java/com/example/classicjeans/util/MarkdownRenderer.java
  src/main/resources/static/css/chat.css
  src/main/resources/static/js/chat.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/layout/layout.html
Labels: Design, Refactor

#112 Feature/front main
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/info/list.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/img/sec01.png
  src/main/resources/static/img/sec02.png
  src/main/resources/static/img/sec03.png
  src/main/resources/static/img/sec04.png
  src/main/resources/static/img/sec05-01.png
  src/main/resources/static/img/sec05.png
  src/main/resources/static/js/kakaomap.js
  src/main/resources/templates/index.html
Labels: Design, Feature, Refactor

#116 refactor: 마이페이지 가족 정보 수정
  src/main/resources/static/css/member/member.css
  src/main/resources/templates/member/mypage.html
Labels: Refactor

#119 feature: 문진 요청에 현재 로그인중인 유저 / 가족 정보 추가
  src/main/java/com/example/classicjeans/addresscode/service/AddressCodeService.java
  src/main/java/com/example/classicjeans/controller/FamilyInfoController.java
  src/main/java/com/example/classicjeans/controller/UserViewController.java
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/entity/DementiaData.java
  src/main/java/com/example/classicjeans/entity/QuestionnaireData.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/FamilyInfoService.java
  src/main/java/com/example/classicjeans/service/SanatoriumService.java
  src/main/resources/static/css/member/member.css
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/signup.html
Labels: Feature

#122 Feature/admin page
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/admin/controller/AdminMemberController.java
  src/main/java/com/example/classicjeans/admin/controller/AdminViewController.java
  src/main/java/com/example/classicjeans/admin/service/AdminMemberService.java
  src/main/java/com/example/classicjeans/admin/service/AdminService.java
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/dto/response/UsersResponse.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/security/UsersDetailService.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/resources/templates/admin/layout/header.html
  src/main/resources/templates/admin/member/member_edit.html
  src/main/resources/templates/admin/member/member_list.html
  src/main/resources/templates/checkout/dementia_list.html
  src/main/resources/templates/member/change_pw_after_find.html
Labels: Feature

#125 Refactor/front and hospital
  src/main/java/com/example/classicjeans/controller/HospitalController.java
  src/main/java/com/example/classicjeans/controller/HospitalViewController.java
  src/main/java/com/example/classicjeans/entity/Hospital.java
  src/main/java/com/example/classicjeans/entity/HospitalData.java
  src/main/java/com/example/classicjeans/repository/HospitalRepository.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/info/list.css
  src/main/resources/static/css/member/member.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/list.js
  src/main/resources/templates/admin/reservation/reservation_edit.html
  src/main/resources/templates/admin/reservation/reservation_list.html
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/edit_family.html
  src/main/resources/templates/member/mypage.html
Labels: Feature, Fix, Refactor

#126 Feature/view checkup
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/controller/CheckupController.java
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanDementiaResponse.java
  src/main/java/com/example/classicjeans/dto/response/AlanQuestionnaireResponse.java
  src/main/java/com/example/classicjeans/entity/DementiaData.java
  src/main/java/com/example/classicjeans/entity/ImprovementSuggestions.java
  src/main/java/com/example/classicjeans/entity/QuestionnaireData.java
  src/main/java/com/example/classicjeans/entity/SummaryEvaluation.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/FamilyInfoService.java
  src/main/resources/Chungbaji.md
  src/main/resources/static/css/checkout/questionnaire.css
  src/main/resources/static/js/checkout.js
  src/main/resources/static/js/questionnaire.js
  src/main/resources/templates/checkout/checkout.html
  src/main/resources/templates/checkout/questionnaire_list.html
Labels: Docs, Feature, Setting

#127 Feature/alen sse api
  src/main/java/com/example/classicjeans/config/AppConfig.java
  src/main/java/com/example/classicjeans/controller/ChatController.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/resources/static/js/chat.js
Labels: Bug, Fix, Refactor

#129 refactor : SSE 챗봇 관련 불필요한 코드 삭제
  src/main/java/com/example/classicjeans/controller/ChatController.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/resources/static/js/chat.js
Labels: Refactor, Rename

#128 Feature/reservation
  src/main/java/com/example/classicjeans/admin/service/AdminService.java
  src/main/java/com/example/classicjeans/controller/ReservationController.java
  src/main/java/com/example/classicjeans/dto/request/ReservationRequest.java
  src/main/java/com/example/classicjeans/dto/response/HospitalResponse.java
  src/main/java/com/example/classicjeans/dto/response/ReservationResponse.java
  src/main/java/com/example/classicjeans/entity/Reservation.java
  src/main/java/com/example/classicjeans/entity/ReservationQueue.java
  src/main/java/com/example/classicjeans/repository/ReservationRepository.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/java/com/example/classicjeans/service/ReservationService.java
  src/main/resources/Chungbaji.md
  src/main/resources/static/js/hospital.js
  src/main/resources/templates/info/hospital_list.html
Labels: Feature

#131 refactor: 챗봇 로딩 중, 페이지 수정
  src/main/resources/static/css/chat.css
  src/main/resources/static/js/chat.js
  src/main/resources/templates/chat/chat.html
Labels: Refactor

#132 Feature/reservation
  src/main/java/com/example/classicjeans/config/AppConfig.java
  src/main/java/com/example/classicjeans/controller/ReservationController.java
  src/main/java/com/example/classicjeans/service/ReservationNotificationService.java
  src/main/resources/templates/layout/header.html
Labels: Feature

#134 Feature/alarm
  src/main/resources/static/css/header.css
  src/main/resources/static/js/header.js
  src/main/resources/static/js/kakaomap.js
  src/main/resources/templates/layout/header.html
Labels: Feature

#135 Feature/건강 검진 관련 페이지 데이터 연결
  src/main/java/com/example/classicjeans/config/AppConfig.java
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/controller/CheckupController.java
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/entity/DementiaData.java
  src/main/java/com/example/classicjeans/entity/QuestionnaireData.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SmokingStatus.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/SessionUserService.java
  src/main/java/com/example/classicjeans/util/RegexPatterns.java
  src/main/resources/static/css/checkout/questionnaire.css
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/js/questionnaire.js
  src/main/resources/templates/checkout/dementia_list.html
  src/main/resources/templates/checkout/questionnaire_list.html
  src/main/resources/templates/checkout/result.html
Labels: Feature, Fix, Refactor

#138 Feature/reservation 예약/security/모니터링
  .github/workflows/build.yml
  build.gradle
  grafana-prometheus-setup/datasource.yml
  grafana-prometheus-setup/docker-compose.yml
  grafana-prometheus-setup/prometheus.yml
  src/main/java/com/example/classicjeans/ClassicJeansApplication.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/ReservationController.java
  src/main/java/com/example/classicjeans/entity/Reservation.java
  src/main/java/com/example/classicjeans/repository/ReservationRepository.java
  src/main/java/com/example/classicjeans/service/ReservationNotificationService.java
  src/main/java/com/example/classicjeans/service/ReservationService.java
  src/main/resources/Chungbaji.md
  src/main/resources/application.properties
  src/main/resources/static/js/header.js
  src/main/resources/static/js/list.js
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/login.html
Labels: Feature

#139 Feature/bazi api
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/AlanBaziController.java
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/controller/MainController.java
  src/main/java/com/example/classicjeans/dto/request/AlanBaziRequest.java
  src/main/java/com/example/classicjeans/repository/AlanBaziRepository.java
  src/main/java/com/example/classicjeans/security/CustomUserDetails.java
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/resources/static/css/index.css
  src/main/resources/templates/index.html
  src/test/java/com/example/classicjeans/controller/AlanBaziControllerTest.java
  src/test/java/com/example/classicjeans/controller/AlanControllerTest.java
Labels: Feature, Refactor

#140 refactor : 오늘의 운세 대답 MarkdownRenderer 적용
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/resources/templates/index.html
Labels: Refactor

#142 Refactor/메인 운세 텍스트 수정 및 스타일 수정
  src/main/java/com/example/classicjeans/dto/request/AlanBaziRequest.java
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: Refactor

#149 Rename/controller
  src/main/java/com/example/classicjeans/controller/AlanController.java
  src/main/java/com/example/classicjeans/controller/rest/AlanBaziController.java
  src/main/java/com/example/classicjeans/controller/rest/AlanController.java
  src/main/java/com/example/classicjeans/controller/rest/ChatController.java
  src/main/java/com/example/classicjeans/controller/rest/FamilyInfoController.java
  src/main/java/com/example/classicjeans/controller/rest/HospitalController.java
  src/main/java/com/example/classicjeans/controller/rest/NursingHomeController.java
  src/main/java/com/example/classicjeans/controller/rest/ReservationController.java
  src/main/java/com/example/classicjeans/controller/rest/SanatoriumController.java
  src/main/java/com/example/classicjeans/controller/rest/UsersController.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/MainController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/controller/view/ViewController.java
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/resources/static/js/chat.js
  src/main/resources/static/js/find_pw.js
  src/main/resources/static/js/header.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/nickname_check.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/withdrawal.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/change_pw_after_find.html
  src/test/java/com/example/classicjeans/controller/AlanBaziControllerTest.java
  src/test/java/com/example/classicjeans/controller/AlanControllerTest.java
Labels: Refactor, Rename

#153 Feature/statistics service
  src/main/java/com/example/classicjeans/dto/response/AlanQuestionnaireResponse.java
  src/main/java/com/example/classicjeans/dto/response/HealthReportResponse.java
  src/main/java/com/example/classicjeans/entity/QuestionnaireData.java
  src/main/java/com/example/classicjeans/enums/questionnaire/AlcoholConsumption.java
  src/main/java/com/example/classicjeans/enums/questionnaire/ChronicDisease.java
  src/main/java/com/example/classicjeans/enums/questionnaire/DietPattern.java
  src/main/java/com/example/classicjeans/enums/questionnaire/ExerciseFrequency.java
  src/main/java/com/example/classicjeans/enums/questionnaire/HospitalVisit.java
  src/main/java/com/example/classicjeans/enums/questionnaire/IndependenceLevel.java
  src/main/java/com/example/classicjeans/enums/questionnaire/Medication.java
  src/main/java/com/example/classicjeans/enums/questionnaire/MoodStatus.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SleepPattern.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SmokingStatus.java
  src/main/java/com/example/classicjeans/enums/questionnaire/SocialParticipation.java
  src/main/java/com/example/classicjeans/enums/questionnaire/WeightChange.java
  src/main/java/com/example/classicjeans/repository/DementiaDataRepository.java
  src/main/java/com/example/classicjeans/repository/QuestionnaireDataRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/HealthReportService.java
  src/main/resources/Chungbaji.md
  src/main/resources/templates/checkout/result.html
Labels: Feature

#150 Feature/statistics
  src/main/java/com/example/classicjeans/controller/CheckupViewController.java
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/img/favicon.ico
  src/main/resources/static/js/chart.js
  src/main/resources/templates/checkout/result.html
  src/main/resources/templates/checkout/result_detail.html
  src/main/resources/templates/checkout/result_list.html
  src/main/resources/templates/checkout/result_statistics.html
  src/main/resources/templates/layout/header.html
Labels: Feature

#151 feature : 검진 결과 페이지 다운로드 버튼 기능 구현
  src/main/resources/templates/checkout/result.html
Labels: Feature

#157 Rename/controller
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/controller/view/ViewController.java
  src/main/java/com/example/classicjeans/email/controller/EmailController.java
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/find_pw.js
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/checkout/checkout.html
  src/main/resources/templates/checkout/checkout_list.html
  src/main/resources/templates/checkout/dementia_list.html
  src/main/resources/templates/checkout/questionnaire_list.html
  src/main/resources/templates/checkout/result_list.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/change_pw_after_find.html
  src/main/resources/templates/member/edit_family.html
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/find_pw.html
  src/main/resources/templates/member/login.html
Labels: Refactor, Remove, Rename

#152 Test/services
  build.gradle
  src/main/java/com/example/classicjeans/admin/service/AdminService.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/rest/ReservationController.java
  src/main/java/com/example/classicjeans/dto/request/FamilyInfoRequest.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/classicjeans/oauth/OAuthAttributes.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/ReservationNotificationService.java
  src/main/java/com/example/classicjeans/service/ReservationService.java
  src/main/resources/static/css/header.css
  src/main/resources/static/js/header.js
  src/main/resources/static/js/signup.js
  src/test/java/com/example/classicjeans/addresscode/service/AddressCodeServiceTest.java
  src/test/java/com/example/classicjeans/admin/service/AdminServiceTest.java
  src/test/java/com/example/classicjeans/email/AuthCodeGeneratorTest.java
  src/test/java/com/example/classicjeans/security/UsersDetailServiceTest.java
  src/test/java/com/example/classicjeans/service/FamilyInfoServiceTest.java
  src/test/java/com/example/classicjeans/service/HospitalServiceTest.java
  src/test/java/com/example/classicjeans/service/NursingHomeServiceTest.java
  src/test/java/com/example/classicjeans/service/ReservationServiceTest.java
  src/test/java/com/example/classicjeans/service/SanatoriumServiceTest.java
  src/test/java/com/example/classicjeans/service/SessionUserServiceTest.java
  src/test/java/com/example/classicjeans/service/UsersServiceTest.java
Labels: Fix, Refactor, Test

#158 Test/controller
  metric-setup/datasource.yml
  metric-setup/docker-compose.yml
  metric-setup/prometheus.yml
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/dto/response/FamilyInfoResponse.java
  src/main/java/com/example/classicjeans/email/controller/EmailController.java
  src/test/java/com/example/classicjeans/controller/AlanBaziControllerTest.java
  src/test/java/com/example/classicjeans/controller/AlanControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/FamilyInfoControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/HospitalControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/NursingHomeControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/ReservationControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/SanatoriumControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/UsersControllerTest.java
  src/test/java/com/example/classicjeans/service/ReservationServiceTest.java
Labels: Refactor, Test

#162 Feat/scrollbar
  src/main/resources/static/css/checkout/questionnaire.css
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/list.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/checkout/dementia_list.html
  src/main/resources/templates/checkout/questionnaire_list.html
  src/main/resources/templates/index.html
  src/main/resources/templates/info/hospital_list.html
  src/main/resources/templates/info/nursing_list.html
  src/main/resources/templates/info/sanatorium_list.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
Labels: Refactor

#167 Refactor/questionnaire list
  src/main/java/com/example/classicjeans/dto/request/FamilyInfoRequest.java
  src/main/resources/static/css/checkout/questionnaire.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/questionnaire.js
  src/main/resources/templates/checkout/questionnaire_list.html
Labels: Fix, Refactor

#166 Test/controller
  Dockerfile
  datasource.yml
  docker-compose.yml
  jmx_exporter_config.yml
  jmx_prometheus_javaagent-0.16.1.jar
  prometheus.yml
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/MainController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/resources/static/js/header.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/admin/admin-index.html
  src/main/resources/templates/admin/member/member-edit.html
  src/main/resources/templates/admin/member/member-list.html
  src/main/resources/templates/admin/reservation/reservation_edit.html
  src/main/resources/templates/admin/reservation/reservation_list.html
  src/main/resources/templates/checkout/checkout-list.html
  src/main/resources/templates/checkout/dementia-list.html
  src/main/resources/templates/checkout/questionnaire-list.html
  src/main/resources/templates/checkout/result-detail.html
  src/main/resources/templates/checkout/result-list.html
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/info/hospital-list.html
  src/main/resources/templates/info/nursing-list.html
  src/main/resources/templates/info/sanatorium-list.html
  src/main/resources/templates/member/change-pw-after-find.html
  src/main/resources/templates/member/change-pw.html
  src/main/resources/templates/member/edit-family.html
  src/main/resources/templates/member/edit-profile.html
  src/main/resources/templates/member/find-id.html
  src/main/resources/templates/member/find-pw.html
  src/test/java/com/example/classicjeans/controller/rest/ReservationControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/UsersControllerTest.java
  src/test/java/com/example/classicjeans/service/ReservationServiceTest.java
Labels: Fix, Refactor, Rename, Test

#171 refactor: return "" 앞에 '/' 제거
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
Labels: Refactor

#169 Feat/result
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/resources/static/css/checkout/result.css
  src/main/resources/templates/checkout/result-detail.html
  src/main/resources/templates/checkout/result-list.html
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
Labels: Refactor

#173 Feature/improve prompt
  src/main/java/com/example/classicjeans/dto/request/AlanDementiaRequest.java
  src/main/java/com/example/classicjeans/dto/request/AlanQuestionnaireRequest.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/util/RegexPatterns.java
Labels: Feature, Refactor

#177 Refactor/view checkup
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/repository/QuestionnaireDataRepository.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/util/RegexPatterns.java
  src/main/resources/static/js/chart.js
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/index.html
Labels: Feature, Fix, Refactor

#179 Refactor/bazi
  src/main/java/com/example/classicjeans/controller/rest/UsersController.java
  src/main/java/com/example/classicjeans/controller/view/MainController.java
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: Refactor

#180 Test/controller
  .github/workflows/build.yml
  src/main/java/com/example/classicjeans/controller/view/MainController.java
  src/main/java/com/example/classicjeans/entity/NursingHomeData.java
  src/main/java/com/example/classicjeans/repository/NursingHomeDataRepository.java
  src/main/java/com/example/classicjeans/service/NursingHomeService.java
  src/main/resources/Chungbaji.md
  src/test/java/com/example/classicjeans/service/NursingHomeServiceTest.java
  src/test/java/com/example/classicjeans/service/UsersServiceTest.java
Labels: Fix, Refactor, Test

#182 Release v1.0.0 버전 update
  .github/workflows/build.yml
  src/main/java/com/example/classicjeans/controller/view/MainController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/resources/application.properties
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/login.html
Labels: Chore, Deploy

#184 Fix/oauth2
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/example/classicjeans/oauth/OAuthAttributes.java
  src/test/java/com/example/classicjeans/admin/controller/AdminControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/CheckupViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/HospitalViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/MainControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/NursingHomeViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/SanatoriumViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/UserViewControllerTest.java
  src/test/java/com/example/classicjeans/email/service/AuthServiceTest.java
  src/test/java/com/example/classicjeans/service/UsersServiceTest.java
Labels: Fix, Refactor, Test

#185 Feature/prevent loggedin
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
Labels: Feature

#190 Fix/user profile
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/dto/request/FamilyInfoRequest.java
  src/main/java/com/example/classicjeans/dto/response/FamilyInfoResponse.java
  src/main/java/com/example/classicjeans/entity/FamilyInfo.java
  src/main/java/com/example/classicjeans/service/FamilyInfoService.java
  src/main/resources/Chungbaji.md
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/member/edit-family.html
  src/main/resources/templates/member/edit-profile.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/signup.html
  src/test/java/com/example/classicjeans/controller/rest/FamilyInfoControllerTest.java
  src/test/java/com/example/classicjeans/service/FamilyInfoServiceTest.java
Labels: Feature, Fix

#192 Refactor/bazi refactor
  src/main/java/com/example/classicjeans/dto/request/AlanBaziRequest.java
  src/main/java/com/example/classicjeans/repository/AlanBaziRepository.java
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/resources/static/js/header.js
  src/main/resources/static/js/index.js
Labels: Fix, Refactor

#191 Refactor/code refactor
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/rest/UsersController.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/security/RedirectIfAuthenticatedFilter.java
  src/main/resources/static/css/checkout/questionnaire.css
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/list.js
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/info/hospital-list.html
  src/main/resources/templates/info/nursing-list.html
  src/main/resources/templates/info/sanatorium-list.html
  src/main/resources/templates/member/success.html
Labels: Fix, Refactor

#188 Feature/alan chat service
  src/main/java/com/example/classicjeans/controller/rest/ChatController.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/resources/static/js/chat.js
  src/main/resources/templates/chat/chat.html
Labels: Fix, Refactor, Rename

#199 Feature/add family
  src/main/resources/static/js/edit_family.js
Labels: Feature

#200 Fix/withdrawal
  prometheus.yml
  src/main/resources/static/js/withdrawal.js
Labels: Fix

#201 Feature/select layout
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/css/member/member.css
  src/main/resources/static/js/edit_family.js
  src/main/resources/templates/checkout/result-list.html
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/member/edit-family.html
  src/main/resources/templates/member/edit-profile.html
  src/main/resources/templates/member/mypage.html
Labels: Refactor

#202 Setting/path
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/java/com/example/classicjeans/service/NursingHomeService.java
  src/main/java/com/example/classicjeans/service/SanatoriumService.java
  src/main/resources/application.properties
Labels: Setting

#203 feat: 통계페이지에 그래프 노출 조건 변경
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
Labels: Fix

#205 fix: 가족 수정 페이지 생년월일 유효성인증 메시지 위치 수정
  src/main/resources/static/js/edit_family.js
Labels: Fix

#207 setting : 환경변수 API KEY static 삭제
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/java/com/example/classicjeans/service/NursingHomeService.java
  src/main/java/com/example/classicjeans/service/SanatoriumService.java
Labels: Fix, Refactor

#209 Fix/view checkout page
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/resources/static/css/member.css
  src/main/resources/templates/member/signup.html
Labels: Fix

#210 fix: 앨런과의 채팅 엔터키
  src/main/resources/static/js/chat.js
Labels: Fix

#197 Release/v1.0.1
  .github/workflows/build.yml
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/rest/ChatController.java
  src/main/java/com/example/classicjeans/controller/rest/UsersController.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/SanatoriumViewController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/dto/request/AlanBaziRequest.java
  src/main/java/com/example/classicjeans/dto/request/FamilyInfoRequest.java
  src/main/java/com/example/classicjeans/dto/response/FamilyInfoResponse.java
  src/main/java/com/example/classicjeans/entity/FamilyInfo.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/example/classicjeans/oauth/OAuthAttributes.java
  src/main/java/com/example/classicjeans/repository/AlanBaziRepository.java
  src/main/java/com/example/classicjeans/security/RedirectIfAuthenticatedFilter.java
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/FamilyInfoService.java
  src/main/resources/Chungbaji.md
  src/main/resources/static/css/checkout/questionnaire.css
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/js/chat.js
  src/main/resources/static/js/common.js
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/header.js
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/list.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/info/hospital-list.html
  src/main/resources/templates/info/nursing-list.html
  src/main/resources/templates/info/sanatorium-list.html
  src/main/resources/templates/member/edit-family.html
  src/main/resources/templates/member/edit-profile.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/signup.html
  src/main/resources/templates/member/success.html
  src/test/java/com/example/classicjeans/admin/controller/AdminControllerTest.java
  src/test/java/com/example/classicjeans/controller/rest/FamilyInfoControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/CheckupViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/HospitalViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/MainControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/NursingHomeViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/SanatoriumViewControllerTest.java
  src/test/java/com/example/classicjeans/controller/view/UserViewControllerTest.java
  src/test/java/com/example/classicjeans/email/service/AuthServiceTest.java
  src/test/java/com/example/classicjeans/service/FamilyInfoServiceTest.java
  src/test/java/com/example/classicjeans/service/UsersServiceTest.java
Labels: Deploy

#211 Release/v1.0.2
  .github/workflows/build.yml
  prometheus.yml
  scripts/deploy.sh
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/service/AlanBaziService.java
  src/main/java/com/example/classicjeans/service/AlanSSEService.java
  src/main/java/com/example/classicjeans/service/AlanService.java
  src/main/java/com/example/classicjeans/service/HospitalService.java
  src/main/java/com/example/classicjeans/service/NursingHomeService.java
  src/main/java/com/example/classicjeans/service/SanatoriumService.java
  src/main/resources/application.properties
  src/main/resources/static/css/checkout/result.css
  src/main/resources/static/css/member.css
  src/main/resources/static/css/member/member.css
  src/main/resources/static/js/chat.js
  src/main/resources/static/js/edit_family.js
  src/main/resources/static/js/withdrawal.js
  src/main/resources/templates/checkout/result-list.html
  src/main/resources/templates/checkout/result-statistics.html
  src/main/resources/templates/member/edit-family.html
  src/main/resources/templates/member/edit-profile.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/signup.html
Labels: Deploy

#216 Refactor/code structure
  src/main/java/com/example/classicjeans/controller/rest/ChatController.java
  src/main/java/com/example/classicjeans/enums/Gender.java
  src/main/java/com/example/classicjeans/enums/questionnaire/CommonFrequency.java
  src/main/java/com/example/classicjeans/enums/questionnaire/MemoryChange.java
  src/main/resources/Chungbaji.md
Labels: Refactor

#215 Refactor/member css
  src/main/resources/static/css/member.css
  src/main/resources/static/css/member/member.css
  src/main/resources/templates/member/success.html
Labels: Refactor

#213 Feature/add swagger
  build.gradle
  docs/diagrams/chat/chat_function.md
  docs/diagrams/information/bazi.md
  docs/diagrams/information/hospital.md
  docs/diagrams/information/support_fund.md
  docs/diagrams/main/main_function.md
  src/main/java/com/example/classicjeans/addresscode/controller/AddressCodeController.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/rest/AlanBaziController.java
  src/main/java/com/example/classicjeans/controller/rest/AlanController.java
  src/main/java/com/example/classicjeans/controller/rest/ChatController.java
  src/main/java/com/example/classicjeans/controller/rest/FamilyInfoController.java
  src/main/java/com/example/classicjeans/controller/rest/HospitalController.java
  src/main/java/com/example/classicjeans/controller/rest/NursingHomeController.java
  src/main/java/com/example/classicjeans/controller/rest/ReservationController.java
  src/main/java/com/example/classicjeans/controller/rest/SanatoriumController.java
  src/main/java/com/example/classicjeans/controller/rest/UsersController.java
  src/main/java/com/example/classicjeans/email/controller/AuthController.java
  src/main/java/com/example/classicjeans/email/controller/EmailController.java
  src/main/resources/templates/member/find-pw.html
Labels: Docs, Feature

#220 Fix/signup
  src/main/java/com/example/classicjeans/controller/rest/FamilyInfoController.java
  src/main/java/com/example/classicjeans/controller/rest/UsersController.java
  src/main/java/com/example/classicjeans/dto/request/SignupRequest.java
  src/main/java/com/example/classicjeans/service/UsersService.java
  src/main/resources/static/js/signup.js
Labels: Fix

#219 docs : README 작성
  README.md
  docs/erd.png
  docs/favicon.ico
  docs/func1.png
  docs/func2.png
  docs/func3.png
  docs/func4.png
  docs/func5.png
  docs/func6.png
  docs/image.png
  docs/mem1.jpg
  docs/mem2.jpg
  docs/mem3.png
  docs/mem4.jpg
  docs/mem5.png
Labels: Docs

#221 refactor : 불 필요한 코드 삭제 및 코드 정렬
  src/main/java/com/example/classicjeans/addresscode/service/AddressCodeService.java
  src/main/java/com/example/classicjeans/admin/controller/AdminController.java
  src/main/java/com/example/classicjeans/config/SecurityConfig.java
  src/main/java/com/example/classicjeans/controller/view/CheckupViewController.java
  src/main/java/com/example/classicjeans/controller/view/HospitalViewController.java
  src/main/java/com/example/classicjeans/controller/view/NursingHomeViewController.java
  src/main/java/com/example/classicjeans/controller/view/UserViewController.java
  src/main/java/com/example/classicjeans/dto/request/AlanHealthRequest.java
  src/main/java/com/example/classicjeans/dto/response/AlanBasicResponse.java
  src/main/java/com/example/classicjeans/entity/SubsidyData.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/example/classicjeans/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/classicjeans/oauth/OAuthAttributes.java
  src/main/java/com/example/classicjeans/repository/AlanBaziRepository.java
  src/main/java/com/example/classicjeans/repository/NursingHomeDataRepository.java
  src/main/java/com/example/classicjeans/repository/ReservationRepository.java
  src/main/java/com/example/classicjeans/repository/SanatoriumDataRepository.java
  src/main/java/com/example/classicjeans/repository/UsersRepository.java
  src/main/java/com/example/classicjeans/security/CustomUserDetails.java
  src/main/java/com/example/classicjeans/security/UsersDetailService.java
  src/main/java/com/example/classicjeans/service/FamilyInfoService.java
  src/main/java/com/example/classicjeans/service/HealthReportService.java
  src/main/java/com/example/classicjeans/service/ReservationService.java
  src/main/java/com/example/classicjeans/service/SanatoriumService.java
  src/main/java/com/example/classicjeans/service/UsersService.java
Labels: Refactor, Rename

#222 docs : README figma 프론트, 관리자 사진 추가
  README.md
  docs/figma_admin.png
  docs/figma_front.png
  docs/figma_front2.png
Labels: Docs

#224 Design/responsiveweb
  src/main/resources/static/css/header.css
  src/main/resources/static/css/index.css
Labels: Design

#225 refactor : 반응형 웹 수정
  src/main/resources/static/css/header.css
Labels: Bug, Design

#229 Refector/css 반응형 수정
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/index.css
Labels: Design, Refactor

#227 feature: CLIENT_ID 변경 로직 추가
  src/main/java/com/example/classicjeans/service/AlanService.java
Labels: Feature, Refactor

#232 Fix/signup
  src/main/resources/static/js/signup.js
Labels: Fix

#231 Docs/readme3
  README.md
  docs/sys1.png
  docs/sys2.png
Labels: Docs

#235 docs: 수정
  README.md
  docs/sys3.png
Labels: Docs
